---
collections:
    - name: community.general
    - name: community.aws
    - name: community.asa
    - name: ansible.eda
    - name: ansible.galaxy_collection
    - name: ansible.posix
    - name: ansible.receptor
    - name: ansible.scm 
