---
collections:
 - name: ansible.controller
 - name: ansible.eda
 - name: ansible.receptor
 - name: microsoft.ad
 - name: test.fail
  # - name: hpe.ilo
    # - name: community.general
    #- name: infra.controller_configuration
   #   version: 4.5.11
  #  - name: azure.azcollection
 #     version: 3.0.0
  #  - name: community.general
  #    version:  9.1.0
   # - name: community.aws
    #  version: 8.0.0
  #  - name: community.asa
   # - name: ansible.posix
    #  version: 1.5.4
    #- name: ansible.eda
  #    version: 1.4.7
   # - name: ansible.galaxy_collection
    #  version: 1.0.13
   # - name: ansible.receptor
 #     version: 2.0.3
  #  - name: ansible.scm
  #    version: 2.0.0
