---
collections:
    - name: infra.controller_configuration
    - name: ansible.controller
  #  - name: community.general
  #    version:  9.1.0
   # - name: community.aws
    #  version: 8.0.0
  #  - name: community.asa
   # - name: ansible.posix
    #  version: 1.5.4
    #- name: ansible.eda
  #    version: 1.4.7
   # - name: ansible.galaxy_collection
    #  version: 1.0.13
 #   - name: ansible.receptor
 #     version: 2.0.3
  #  - name: ansible.scm
  #    version: 2.0.0
