---
- name: Set up daily scan cron job
  hosts: all
  become: true  # Ensure the task runs as root
  tasks:
    - name: Remove existing defender daily cron job
      cron:
        name: defender daily
        state: absent
    - name: Debug current cron jobs
      command: crontab -l
      register: cron_output
      ignore_errors: true  # Optional: in case crontab is empty

    - name: Show crontab output
      debug:
        var: cron_output.stdout_lines
