---
- name: Fetch Ansible facts from a server
  hosts: all
  gather_facts: true  # Ensures facts are collected
  tasks:
    - name: Display all facts
      debug:
        var: ansible_facts

    #- name: Display specific fact - OS Distribution
     # debug:
     #   msg: "The OS distribution is {{ ansible_facts['ansible_distribution'] }}"

    - name: Display specific fact - Hostname
      debug:
        msg: "The hostname is {{ ansible_facts['all_ipv4_addresses'] }}"
