- name: hpe server component level playbook
  hosts: localhost
  gather_facts: no
  roles:
    - role: hpe.ilo.set_secure_boot
  #    vars:
  #      baseuri: "{{ ilo_address }}"
  #      username: "{{ ilo_username }}"
  #      password: "{{ ilo_password }}"
        secure_boot_enable: True       
  tasks:
    - name: Enable secure boot
      ansible.builtin.debug:
        msg: "Next task will call role to enable secure boot for {{ ilo_address }}"
