---
- name: Print variable with new line
  hosts: localhost
  gather_facts: false
  vars:
    my_variable: "Hello, Ansible!"

  tasks:
    - name: Print variable with a new line
      ansible.builtin.debug:
        msg: "{{ my_variable }}\n"
