---
- name: Vars test
  hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  gather_facts: false

  tasks: 
    - name: debugging vars
      ansible.builtin.debug:
        msg: "{{ credentials }}"
