---
- name: "Create AIP credentials on {{ controller_hostname }}"
  hosts: all
  gather_facts: false
  no_log: false
  vars:
    controller_hostname: "dhcp230-13.awxlab.pnq2.redhat.com"
    ssh_username: "root"  # Define your SSH username here
    ssh_private_key: "{{ lookup('file', 'ssh_key') }}"
      
    controller_credentials:
      - name: "AIP SSH Server key"
        description: "SSH key to access AIP Server"
        organization: "Default"
        credential_type: "Machine"
        state: "present"
        inputs:
          username: "{{ ssh_username }}"
          ssh_key_data: "{{ ssh_private_key | default(omit) }}"

  tasks:
    - name: "Create credentials - {{ controller_hostname }}"
      ansible.builtin.include_role:
        name: infra.controller_configuration.credentials
      no_log: false  
      when: controller_credentials is defined
